-- ============================================================================
-- Black Hole Basin – Monitoring Wells Schema
-- ============================================================================
-- Requires PostGIS:  CREATE EXTENSION IF NOT EXISTS postgis;
--
-- HOW TO READ THIS FILE:
--   This is a SQL "migration" — you run it against a PostgreSQL database, and
--   it creates all the tables, types, and indexes your app needs. Think of it
--   as a blueprint for how your data is organized.
--
-- KEY CONCEPTS USED BELOW:
--
--   UUID PRIMARY KEY
--     Every row gets a universally unique ID (a 128-bit random string like
--     "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"). Your API generates these
--     before inserting. Safer than auto-incrementing integers because they
--     don't reveal how many records you have and won't collide across systems.
--
--   NOT NULL
--     Means the column MUST have a value — Postgres will reject any insert
--     that leaves it blank. If a column doesn't say NOT NULL, it's optional
--     and can be left empty (NULL).
--
--   UNIQUE
--     No two rows can have the same value in this column. If someone tries
--     to register with an email that already exists, Postgres blocks it.
--
--   DEFAULT
--     If you don't provide a value, Postgres fills it in for you.
--     "DEFAULT now()" means "use the current timestamp."
--
--   REFERENCES ... ON DELETE CASCADE / RESTRICT
--     A foreign key — it points to a row in another table.
--       CASCADE  = if the parent row is deleted, delete this row too.
--       RESTRICT = if the parent row has children, BLOCK the delete.
--
--   TEXT vs CHAR(n)
--     TEXT = unlimited length string (Postgres handles this efficiently).
--     CHAR(n) = fixed-width string, always exactly n characters (padded
--     with spaces if shorter). Only use CHAR when every value is truly the
--     same length, like a 2-letter state code or a 97-char bcrypt hash.
--
--   NUMERIC vs FLOAT
--     FLOAT stores numbers in binary — fast but can have tiny rounding
--     errors (e.g., 0.1 + 0.2 = 0.30000000000000004). NUMERIC stores
--     numbers as exact decimals. For measurements like well depth or
--     altitude where precision matters for display, NUMERIC is safer.
--
--   TIMESTAMPTZ
--     A timestamp WITH timezone. Postgres converts everything to UTC for
--     storage and converts back to your session timezone on read. Always
--     use this over plain TIMESTAMP — it prevents timezone bugs.
--
--   INDEX
--     Think of it like an index in a textbook — instead of scanning every
--     page (row) to find what you want, Postgres can jump straight to it.
--     You add indexes on columns you search/filter/sort by often.
--
--   GIST INDEX
--     A special kind of index for spatial (geographic) data. Lets PostGIS
--     quickly answer questions like "find all wells within 10 miles."
-- ============================================================================


-- Drop tables in reverse dependency order so foreign keys don't complain.
-- (You can only drop a table if nothing else points to it.)
DROP TABLE IF EXISTS estimates;
DROP TABLE IF EXISTS user_configs;
DROP TABLE IF EXISTS well_data;
DROP TABLE IF EXISTS monitoring_wells;
DROP TABLE IF EXISTS user_activations;
DROP TABLE IF EXISTS users;


-- ============================================================================
-- ENUM TYPES
-- ============================================================================
-- An ENUM is a column type that only allows specific values — like a dropdown.
-- If your API tries to insert role = 'superadmin', Postgres rejects it.
-- This is safer than just using TEXT because typos and bad data can't sneak in.
--
-- The DO $$ ... $$ block is a workaround: CREATE TYPE fails if the type
-- already exists, so we check first. You only need this if you might run
-- the script more than once without dropping the type.

DO
$$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
      CREATE TYPE USER_ROLE AS ENUM ('admin', 'user');
    END IF;
  END
$$;


-- ============================================================================
-- USERS
-- ============================================================================
-- One row per person who can log into Black Hole Basin.

CREATE TABLE IF NOT EXISTS users
(
  id         UUID PRIMARY KEY,                    -- generated by your API (e.g., crypto.randomUUID())
  email      TEXT        NOT NULL UNIQUE,         -- login identifier; UNIQUE prevents duplicate accounts
  hash       CHAR(97)    NOT NULL,                -- bcrypt password hash (always exactly 97 chars)
  name       TEXT        NOT NULL,                -- display name
  role       USER_ROLE   NOT NULL DEFAULT 'user', -- admin or user; new signups default to user
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),  -- auto-set on insert
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()   -- your API should update this on every edit
);


-- ============================================================================
-- USER ACTIVATIONS
-- ============================================================================
-- When a new user signs up, you create a row here with a random token and
-- email them a link like: https://app.blackholebasin.com/activate?token=abc123
-- When they click it, your API verifies the token + checks expires_at,
-- then deletes this row. The user is now "activated."
--
-- This is a separate table instead of columns on `users` because:
--   1. Most users only need this once — no point storing dead columns forever.
--   2. The PRIMARY KEY is user_id (not a separate id), so each user can only
--      have one pending activation at a time.
--   3. ON DELETE CASCADE means if you delete the user, this cleans up too.

CREATE TABLE IF NOT EXISTS user_activations
(
  user_id    UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  token      CHAR(32)    NOT NULL,                                       -- random 32-char hex token
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '24 hours'), -- link dies after 24h
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================================
-- MONITORING WELLS
-- ============================================================================
-- Each row is one physical well site, typically sourced from the USGS NWIS
-- (National Water Information System) data pipeline.
--
-- ON DELETE RESTRICT on user_id means: if a user owns wells, you CANNOT
-- delete that user until you reassign or remove their wells first. This
-- prevents accidentally orphaning well records.

CREATE TABLE IF NOT EXISTS monitoring_wells
(
  id            UUID PRIMARY KEY,
  user_id       UUID                  NOT NULL REFERENCES users (id) ON DELETE RESTRICT,

  -- USGS metadata (nullable because not every site has complete data)
  location_id   TEXT,                           -- USGS site number (e.g., "354231106411801")
  location_name TEXT,                           -- human-readable site name from USGS

  -- PostGIS geometry column: stores lat/lon as a single geographic point.
  -- 4326 = the SRID (spatial reference ID) for standard GPS coordinates
  -- (WGS 84 — the same system your phone uses).
  -- To insert: ST_SetSRID(ST_MakePoint(-106.65, 34.52), 4326)
  -- To read:   ST_X(geom) -> longitude,  ST_Y(geom) -> latitude
  geom          GEOMETRY(Point, 4326) NOT NULL,

  state_code    CHAR(2)               NOT NULL, -- FIPS code, e.g., "35" for New Mexico
  county_name   TEXT,                           -- county name, e.g., "Valencia County"
  altitude      NUMERIC,                        -- land surface elevation (ft above sea level)
  hole_depth    NUMERIC,                        -- total depth drilled (ft)
  well_depth    NUMERIC,                        -- completed/usable depth (ft), often shallower than hole_depth
  date_drilled  TIMESTAMPTZ,                    -- when the well was originally drilled

  created_at    TIMESTAMPTZ           NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ           NOT NULL DEFAULT now()
);

-- Speed up "show me all wells for this user" queries.
CREATE INDEX idx_monitoring_wells_user_id ON monitoring_wells (user_id);

-- GIST index on the geometry column — required for fast spatial queries like:
--   SELECT * FROM monitoring_wells
--   WHERE ST_DWithin(geom, ST_MakePoint(-106.65, 34.52)::geography, 16093);
--   (finds all wells within 10 miles / 16,093 meters of a point)
CREATE INDEX idx_monitoring_wells_geom ON monitoring_wells USING GIST (geom);


-- ============================================================================
-- WELL DATA (time-series water level readings)
-- ============================================================================
-- Each row is a single water-level measurement for a well at a point in time.
-- A well might have thousands of these — one per day/week/month going back
-- decades. This is the core data your app visualizes.
--
-- ON DELETE CASCADE: if a well record is deleted, all its readings go too.
-- (You'd never want orphaned readings pointing at a well that doesn't exist.)

CREATE TABLE IF NOT EXISTS well_data
(
  id                 UUID PRIMARY KEY,
  monitoring_well_id UUID        NOT NULL REFERENCES monitoring_wells (id) ON DELETE CASCADE,
  depth_to_water     NUMERIC     NOT NULL, -- feet below land surface to the water table
  date_measured      TIMESTAMPTZ NOT NULL, -- when this reading was taken
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Speed up "show me all readings for this well" queries.
CREATE INDEX idx_well_data_well_id ON well_data (monitoring_well_id);

-- Speed up "show me all readings across all wells on this date" queries.
CREATE INDEX idx_well_data_date_measured ON well_data (date_measured);

-- COMPOSITE INDEX: covers the most common query pattern — "get all readings
-- for well X, sorted by date." Postgres can satisfy this entirely from the
-- index without touching the actual table rows, which is significantly faster.
-- Think of it as a textbook index sorted first by well, then by date within
-- each well's section.
CREATE INDEX idx_well_data_well_date ON well_data (monitoring_well_id, date_measured);


-- ============================================================================
-- USER CONFIGS (pricing and specification defaults for estimates)
-- ============================================================================
-- Each row is a named configuration that a user can create and reuse across
-- multiple estimates. A user might have "Residential Standard", "Commercial
-- Deep Well", etc. with different pricing and specs for each.
--
-- ON DELETE CASCADE: if the user is deleted, their configs go too.
-- casing_prices and screen_prices are JSONB objects keyed by diameter in
-- inches, e.g. { "4": 12.50, "6": 18.75 }

CREATE TABLE IF NOT EXISTS user_configs
(
  id                 UUID PRIMARY KEY,
  user_id            UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name               TEXT        NOT NULL,              -- label like "Residential Standard"
  cost_per_foot      JSONB       NOT NULL DEFAULT '{}', -- drilling cost per foot
  mobilization_fee   NUMERIC     NOT NULL DEFAULT 0,    -- flat fee for mobilizing equipment
  casing_prices      JSONB       NOT NULL DEFAULT '{}', -- diameter-to-price mapping
  screen_prices      JSONB       NOT NULL DEFAULT '{}', -- diameter-to-price mapping
  slot_size          NUMERIC     NOT NULL,              -- screen slot size
  gravel_pack_prices JSONB       NOT NULL DEFAULT '{}', -- gravel pack grain size
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Speed up "show me all configs for this user" queries.
CREATE INDEX idx_user_configs_user_id ON user_configs (user_id);


-- ============================================================================
-- ESTIMATES (persisted well drilling estimates)
-- ============================================================================
-- Each row is a saved estimate combining user input (location, water demand),
-- calculated results (depth, casing, screen), and cost breakdown. References
-- the nearest monitoring well used for the calculation and the user config
-- that provided pricing.
--
-- ON DELETE RESTRICT on user_config_id: don't allow deleting a config that
-- has estimates referencing it — the user should reassign or delete the
-- estimates first.

CREATE TABLE IF NOT EXISTS estimates
(
  id                         UUID PRIMARY KEY,
  user_id                    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  user_config_id             UUID        NOT NULL REFERENCES user_configs (id) ON DELETE RESTRICT,
  nearest_monitoring_well_id UUID        NOT NULL REFERENCES monitoring_wells (id) ON DELETE RESTRICT,

  -- User input
  input_lat                  NUMERIC     NOT NULL,
  input_lon                  NUMERIC     NOT NULL,
  water_demand_gpm           NUMERIC     NOT NULL,

  -- Calculated results
  estimated_depth            NUMERIC     NOT NULL,
  altitude_difference        NUMERIC     NOT NULL,
  depth_to_water             NUMERIC     NOT NULL,
  casing_diameter            NUMERIC     NOT NULL, -- inches
  screen_length              NUMERIC     NOT NULL, -- feet
  slot_size                  NUMERIC     NOT NULL,

  -- Cost breakdown
  drilling_cost              NUMERIC     NOT NULL,
  screen_cost                NUMERIC     NOT NULL,
  gravel_pack_cost           NUMERIC     NOT NULL,
  mobilization_cost          NUMERIC     NOT NULL,
  total_cost                 NUMERIC     NOT NULL,

  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Speed up "show me all estimates for this user" queries.
CREATE INDEX idx_estimates_user_id ON estimates (user_id);